# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nazwa')),
                ('quantity', models.FloatField(verbose_name='Ilo\u015b\u0107')),
                ('unit', models.CharField(choices=[('szt', 'Sztuka'), ('g', 'Gram'), ('ml', 'Mililitr')], max_length=30, verbose_name='Jednostka')),
            ],
            options={
                'verbose_name': 'Sk\u0142adnik',
                'verbose_name_plural': 'Sk\u0142adniki',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa')),
                ('level', models.CharField(choices=[('easy', '\u0141atwy'), ('medium', '\u015aredni'), ('hard', 'Trudny')], max_length=10, verbose_name='Poziom trudno\u015bci')),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredient', verbose_name='Sk\u0142adniki')),
            ],
            options={
                'verbose_name': 'Przepis',
                'verbose_name_plural': 'Przepisy',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Opis')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Kolejno\u015b\u0107')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe', verbose_name='Przepis')),
            ],
            options={
                'verbose_name': 'Krok',
                'verbose_name_plural': 'Kroki',
            },
        ),
    ]
